/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimitivesRouteImport } from './routes/primitives'
import { Route as HeroPreviewRouteImport } from './routes/hero-preview'
import { Route as DesignTokensRouteImport } from './routes/design-tokens'
import { Route as AccountRouteImport } from './routes/account'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopHandleRouteImport } from './routes/shop/$handle'

const PrimitivesRoute = PrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroPreviewRoute = HeroPreviewRouteImport.update({
  id: '/hero-preview',
  path: '/hero-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignTokensRoute = DesignTokensRouteImport.update({
  id: '/design-tokens',
  path: '/design-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopHandleRoute = ShopHandleRouteImport.update({
  id: '/shop/$handle',
  path: '/shop/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
  '/account': typeof AccountRoute
  '/journal': typeof JournalRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopIndexRoute
  '/shop/$handle': typeof ShopHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
  '/account': typeof AccountRoute
  '/journal': typeof JournalRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopIndexRoute
  '/shop/$handle': typeof ShopHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
  '/account': typeof AccountRoute
  '/journal': typeof JournalRoute
  '/checkout': typeof CheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/$handle': typeof ShopHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-tokens' | '/hero-preview' | '/primitives' | '/account' | '/journal' | '/checkout' | '/shop' | '/shop/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-tokens' | '/hero-preview' | '/primitives' | '/account' | '/journal' | '/checkout' | '/shop' | '/shop/$handle'
  id: '__root__' | '/' | '/design-tokens' | '/hero-preview' | '/primitives' | '/account' | '/journal' | '/checkout' | '/shop/' | '/shop/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignTokensRoute: typeof DesignTokensRoute
  HeroPreviewRoute: typeof HeroPreviewRoute
  PrimitivesRoute: typeof PrimitivesRoute
  AccountRoute: typeof AccountRoute
  JournalRoute: typeof JournalRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopHandleRoute: typeof ShopHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primitives': {
      id: '/primitives'
      path: '/primitives'
      fullPath: '/primitives'
      preLoaderRoute: typeof PrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-preview': {
      id: '/hero-preview'
      path: '/hero-preview'
      fullPath: '/hero-preview'
      preLoaderRoute: typeof HeroPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-tokens': {
      id: '/design-tokens'
      path: '/design-tokens'
      fullPath: '/design-tokens'
      preLoaderRoute: typeof DesignTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$handle': {
      id: '/shop/$handle'
      path: '/shop/$handle'
      fullPath: '/shop/$handle'
      preLoaderRoute: typeof ShopHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignTokensRoute: DesignTokensRoute,
  HeroPreviewRoute: HeroPreviewRoute,
  PrimitivesRoute: PrimitivesRoute,
  AccountRoute: AccountRoute,
  JournalRoute: JournalRoute,
  CheckoutRoute: CheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopHandleRoute: ShopHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
