/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimitivesRouteImport } from './routes/primitives'
import { Route as HeroPreviewRouteImport } from './routes/hero-preview'
import { Route as DesignTokensRouteImport } from './routes/design-tokens'
import { Route as IndexRouteImport } from './routes/index'

const PrimitivesRoute = PrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroPreviewRoute = HeroPreviewRouteImport.update({
  id: '/hero-preview',
  path: '/hero-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignTokensRoute = DesignTokensRouteImport.update({
  id: '/design-tokens',
  path: '/design-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-tokens': typeof DesignTokensRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/primitives': typeof PrimitivesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-tokens' | '/hero-preview' | '/primitives'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-tokens' | '/hero-preview' | '/primitives'
  id: '__root__' | '/' | '/design-tokens' | '/hero-preview' | '/primitives'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignTokensRoute: typeof DesignTokensRoute
  HeroPreviewRoute: typeof HeroPreviewRoute
  PrimitivesRoute: typeof PrimitivesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primitives': {
      id: '/primitives'
      path: '/primitives'
      fullPath: '/primitives'
      preLoaderRoute: typeof PrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-preview': {
      id: '/hero-preview'
      path: '/hero-preview'
      fullPath: '/hero-preview'
      preLoaderRoute: typeof HeroPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-tokens': {
      id: '/design-tokens'
      path: '/design-tokens'
      fullPath: '/design-tokens'
      preLoaderRoute: typeof DesignTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignTokensRoute: DesignTokensRoute,
  HeroPreviewRoute: HeroPreviewRoute,
  PrimitivesRoute: PrimitivesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
